[project]
name = "aclarknet"
version = "0.1.0"
dependencies = [
  "django-import-export",
  "django-mongodb-backend",
  "django-phonenumber-field",
  "phonenumbers",
  "python-webpack-boilerplate",
  "wagtail",
]

[tool.setuptools]
packages = ["aclarknet", "db"]
